# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from utils import service_pb2 as service__pb2


class CommunicationServiceStub(object):
    """The service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.step = channel.unary_unary(
                '/communication.CommunicationService/step',
                request_serializer=service__pb2.StepRequest.SerializeToString,
                response_deserializer=service__pb2.StepReply.FromString,
                )


class CommunicationServiceServicer(object):
    """The service definition.
    """

    def step(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CommunicationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'step': grpc.unary_unary_rpc_method_handler(
                    servicer.step,
                    request_deserializer=service__pb2.StepRequest.FromString,
                    response_serializer=service__pb2.StepReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'communication.CommunicationService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class CommunicationService(object):
    """The service definition.
    """

    @staticmethod
    def step(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/communication.CommunicationService/step',
            service__pb2.StepRequest.SerializeToString,
            service__pb2.StepReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
